development: &default
  adapter: postgresql
  database: copycopter_development
  username: postgres
  password: postgres
  min_messages: WARNING

test: &test
  <<: *default
  database: copycopter_test

production: &production
  <<: *default
  database: copycopter
